### ISSUE TITLE
Does not work with webpack 4.1.1

### ISSUE THREAD

**Issue by yolinas** [gabiseabra/fontello-webpack-plugin#18]
Tried to update Webpack to the latest major version (4.1.1) and I get the following stack trace:

```
ERROR in   TypeError: cb is not a function
  - index.js:54 compilation.plugin
    [web-agent-portal]/[fontello-webpack-plugin]/src/index.js:54:5
  - new Promise
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [web-agent-portal]/[tapable]/lib/Hook.js:35:21
  - index.js:647 
    [web-agent-portal]/[html-webpack-plugin]/index.js:647:47
  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [web-agent-portal]/[html-webpack-plugin]/index.js:162:36
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```

They have made some breaking changes in webpack 4.x and I suspect some update needs to be done to this plugin. Any idea when it could be fixed?

Thanks

**Comment by ValentinFunk** [comment]
See #19 
@gabiseabra please merge if possible :) Much appreciated!

**Comment by ValentinFunk** [comment]
ping @gabiseabra

**Comment by patlux** [comment]
@gabiseabra

**Comment by willhowlett** [comment]
+1

**Comment by tomtomau** [comment]
+1+ Merging this would be much appreciated @gabiseabra

**Comment by tomtomau** [comment]
I was able to get this plugin working with Webpack 4.17.1 but required a bit of fiddling.

Install @sypl's fork which is the pull request #19

```
yarn add https://github.com/sypl/fontello-webpack-plugin.git#35dac8cfd851bc1b3be19fd97e361516a1be6633 --dev
```

I also needed to install the html-webpack-plugin:

```
yarn add html-webpack-plugin --dev
```

I then needed to update my webpack config:

```
const FontelloPlugin = require('fontello-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin'); // Add this line
const path = require('path');

module.exports = {
  entry: './assets/fonts/index.js', // This is just an empty file
  output: {
    path: path.resolve(__dirname, 'public/fonts'),
    filename: '[name].js'
  },
  plugins: [
    new FontelloPlugin({
      config: require('./assets/fonts/fontello')
    }),
    new HtmlWebpackPlugin() // Add this line
  ]
};
```

And then my config was working and it was now building the fonts.
